export const categoriesData = [
  {
    title: "Dairy & Other Perishables",
    items: [
      {
        id: 1,
        name: "Milk",
        price: 2.99,
        unit: [2, 3, 4],
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Milk+2",
          "https://via.placeholder.com/120x120.png?text=Milk+3",
          "https://via.placeholder.com/120x120.png?text=Milk+4",
        ],
      },
      {
        id: 2,
        name: "Cheese",
        price: 4.99,
        unit: [2, 3, 4],
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Cheese+2",
          "https://via.placeholder.com/120x120.png?text=Cheese+3",
          "https://via.placeholder.com/120x120.png?text=Cheese+4",
        ],
      },
      {
        id: 3,
        name: "Yogurt",
        price: 1.99,
        unit: [2, 3, 4],
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Yogurt+2",
          "https://via.placeholder.com/120x120.png?text=Yogurt+3",
          "https://via.placeholder.com/120x120.png?text=Yogurt+4",
        ],
      },
      {
        id: 4,
        name: "Butter",
        price: 3.49,
        unit: [2, 3, 4],
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Butter+2",
          "https://via.placeholder.com/120x120.png?text=Butter+3",
          "https://via.placeholder.com/120x120.png?text=Butter+4",
        ],
      },
      {
        id: 5,
        name: "Eggs",
        price: 2.5,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Eggs+2",
          "https://via.placeholder.com/120x120.png?text=Eggs+3",
          "https://via.placeholder.com/120x120.png?text=Eggs+4",
        ],
      },
      {
        id: 6,
        name: "Cream",
        price: 2.79,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Cream+2",
          "https://via.placeholder.com/120x120.png?text=Cream+3",
          "https://via.placeholder.com/120x120.png?text=Cream+4",
        ],
      },
      {
        id: 7,
        name: "Sour Cream",
        price: 3.29,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=SourCream+2",
          "https://via.placeholder.com/120x120.png?text=SourCream+3",
          "https://via.placeholder.com/120x120.png?text=SourCream+4",
        ],
      },
      {
        id: 8,
        name: "Cottage Cheese",
        price: 2.89,
        unit: [2, 3, 4],
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=CottageCheese+2",
          "https://via.placeholder.com/120x120.png?text=CottageCheese+3",
          "https://via.placeholder.com/120x120.png?text=CottageCheese+4",
        ],
      },
      {
        id: 9,
        name: "Ice Cream",
        price: 5.99,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=IceCream+2",
          "https://via.placeholder.com/120x120.png?text=IceCream+3",
          "https://via.placeholder.com/120x120.png?text=IceCream+4",
        ],
      },
      {
        id: 10,
        name: "Whipped Cream",
        price: 3.59,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=WhippedCream+2",
          "https://via.placeholder.com/120x120.png?text=WhippedCream+3",
          "https://via.placeholder.com/120x120.png?text=WhippedCream+4",
        ],
      },
    ],
  },
  {
    title: "Snacks & Beverages",
    items: [
      {
        id: 11,
        name: "Chips",
        price: 1.99,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Chips+2",
          "https://via.placeholder.com/120x120.png?text=Chips+3",
          "https://via.placeholder.com/120x120.png?text=Chips+4",
        ],
      },
      {
        id: 12,
        name: "Soda",
        price: 1.5,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Soda+2",
          "https://via.placeholder.com/120x120.png?text=Soda+3",
          "https://via.placeholder.com/120x120.png?text=Soda+4",
        ],
      },
      {
        id: 13,
        name: "Cookies",
        price: 2.99,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Cookies+2",
          "https://via.placeholder.com/120x120.png?text=Cookies+3",
          "https://via.placeholder.com/120x120.png?text=Cookies+4",
        ],
      },
      {
        id: 14,
        name: "Juice",
        price: 2.0,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Juice+2",
          "https://via.placeholder.com/120x120.png?text=Juice+3",
          "https://via.placeholder.com/120x120.png?text=Juice+4",
        ],
      },
      {
        id: 15,
        name: "Candy",
        price: 0.99,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Juice+2",
          "https://via.placeholder.com/120x120.png?text=Juice+3",
          "https://via.placeholder.com/120x120.png?text=Juice+4",
        ],
      },
      {
        id: 16,
        name: "Nuts",
        price: 3.49,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Juice+2",
          "https://via.placeholder.com/120x120.png?text=Juice+3",
          "https://via.placeholder.com/120x120.png?text=Juice+4",
        ],
      },
      {
        id: 17,
        name: "Granola Bars",
        price: 1.79,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Juice+2",
          "https://via.placeholder.com/120x120.png?text=Juice+3",
          "https://via.placeholder.com/120x120.png?text=Juice+4",
        ],
      },
      {
        id: 18,
        name: "Energy Drink",
        price: 2.49,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Juice+2",
          "https://via.placeholder.com/120x120.png?text=Juice+3",
          "https://via.placeholder.com/120x120.png?text=Juice+4",
        ],
      },
    ],
  },
  {
    title: "Spices & Ingredients",
    items: [
      {
        id: 19,
        name: "Salt",
        price: 0.99,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Salt+2",
          "https://via.placeholder.com/120x120.png?text=Salt+3",
          "https://via.placeholder.com/120x120.png?text=Salt+4",
        ],
      },
      {
        id: 20,
        name: "Pepper",
        price: 1.49,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Pepper+2",
          "https://via.placeholder.com/120x120.png?text=Pepper+3",
          "https://via.placeholder.com/120x120.png?text=Pepper+4",
        ],
      },
      {
        id: 21,
        name: "Oregano",
        price: 1.29,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Oregano+2",
          "https://via.placeholder.com/120x120.png?text=Oregano+3",
          "https://via.placeholder.com/120x120.png?text=Oregano+4",
        ],
      },
      {
        id: 22,
        name: "Basil",
        price: 1.19,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Basil+2",
          "https://via.placeholder.com/120x120.png?text=Basil+3",
          "https://via.placeholder.com/120x120.png?text=Basil+4",
        ],
      },
      {
        id: 23,
        name: "Cumin",
        price: 1.39,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Basil+2",
          "https://via.placeholder.com/120x120.png?text=Basil+3",
          "https://via.placeholder.com/120x120.png?text=Basil+4",
        ],
      },
      {
        id: 24,
        name: "Paprika",
        price: 1.49,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Basil+2",
          "https://via.placeholder.com/120x120.png?text=Basil+3",
          "https://via.placeholder.com/120x120.png?text=Basil+4",
        ],
      },
      {
        id: 25,
        name: "Garlic Powder",
        price: 1.29,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Basil+2",
          "https://via.placeholder.com/120x120.png?text=Basil+3",
          "https://via.placeholder.com/120x120.png?text=Basil+4",
        ],
      },
      {
        id: 26,
        name: "Onion Powder",
        price: 1.29,
        images: [
          "https://via.placeholder.com/120x120.png",
          "https://via.placeholder.com/120x120.png?text=Basil+2",
          "https://via.placeholder.com/120x120.png?text=Basil+3",
          "https://via.placeholder.com/120x120.png?text=Basil+4",
        ],
      },
    ],
  },
];
